name: Android CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Debug - Print gradle-wrapper.properties
      run: cat gradle/wrapper/gradle-wrapper.properties

    - name: Debug - Check disk space before build
      run: df -h

    - name: Debug - Download Gradle distribution manually
      run: |
        curl -L -o gradle-8.2-bin.zip https://services.gradle.org/distributions/gradle-8.2-bin.zip
        ls -lh gradle-8.2-bin.zip
        unzip -l gradle-8.2-bin.zip

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Debug - Check disk space after build
      run: df -h

    - name: Debug - List gradle dists directory
      run: ls -lR ~/.gradle/wrapper/dists || true

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk